feat(gitbrowse): open commit when word is valid hash
folke/snacks.nvim pull request #161
Opened 2024-11-25 19:54 UTC by dpetka2001

## Description
`gitbrowse` opens commit when word under cursor is valid commit hash. Please check the pattern I used as I'm not confident as to if it covers all the cases. I only tested with `diffview` file history and `gitsigns` blame buffer as I don't use other tools.

## Related Issue(s)
Closes #138.

## Screenshots

2024-11-26 10:23 UTC, dpetka2001 commented
I tried to change the logic of the initial commit in accordance to how it already is, so that we don't need the additional `if..else` check. Hopefully this is more preferable? Please do make any changes you deem necessary.

2024-11-26 10:47 UTC, dpetka2001 commented
Another thing to mind is, maybe we should store the function call in a variable at the top like `local is_commit = is_valid_commit_hash(word)` and then use `is_commit` in the next steps, so that the function call doesn't happen in every step of `opts.what` evaluation?

2024-11-26 15:31 UTC, krishna-bala commented
One thing I noticed is that `git rev-parse --verify {hash}` is called from the current working directory, which is not necessarily the same as the "project root" identified by `:LazyRoot`. Would be nice if we could leverage `:LazyRoot`, but not sure how we can do that without making LazyVim a dependency of snacks.nvim.

2024-11-26 17:04 UTC, krishna-bala commented
Sorry I didn't explain the situation well. 

Let's say I open two buffers, `~/projectA/fileA.lua` and `~/projectB/fileB.lua`. 

I set my working directory to `~/projectA` (via `:chdir ~/projectA`). 

Scenario 1: 
When focused on the `~/projectA/fileA.lua` buffer, I call `:Gitsigns blame`. This opens a new `gitsigns-blame` window. I place my cursor on a commit hash in that `gitsigns-blame` window and call `:lua Snacks.gitbrowse()`. This opens the commit in my browser as expected.

Scenario 2: 
If I don't update the `cwd` and try the same workflow from the `~/projectB/fileB.lua` buffer (open a `gitsigns-blame`, place cursor on commit hash, call `:lua Snacks.gitbrowse()`), I get the "Invalid commit hash" error message.

---

My previous comment was more to say: it would be nice if `Snacks.gitbrowse()` was aware of the project context and didn't require the user to `:chdir ~/projectB` before calling `:lua Snacks.gitbrowse()` for scenario 2.

I tried making a change to the `system` call to use `require("lazyvim.util.root").get()` like so:

`system({ "git", "-C", require("lazyvim.util.root").get(), "rev-parse", "--verify", hash }, "Invalid commit hash")`

But that doesn't work because the `require("lazyvim.util.root").get()` is called from the `gitsigns-blame` window, which is a scratch window in the `cwd`.

2024-11-26 18:40 UTC, dpetka2001 commented
I don't believe there's an easy way to do that. `gitsigns` and `diffview` are both not associated with any buffer. How can you determine the `git_root` directory without providing a file?

 I believe the most prudent thing would be to let the user change the `cwd` himself. You can easily create a mapping to `:cd expand("%:h")` for example.

2024-11-27 10:45 UTC, dpetka2001 commented
@krishna-bala So, I managed to hack something to get around the `cwd` by using the alternate buffer, but I believe there are disadvantages as there might be quite a few edge cases. 

I managed to make it work with `gitsigns` and `diffview`, because both of them open in the correct repo of the tracked file when you invoke their corresponding commands. `neogit` also works if you invoke it with `Neogit cwd=%:p:h`, but I don't know how other tools would behave and I'm afraid there might be edge cases not currently taken into account.

In my personal opinion, I believe it would be better that the handling of the `cwd` would be left up to the user. 

@folke What do you think about that? Should I push my latest changes that take `cwd` of different repos into account or not? I don't expect an immediate answer. Whenever you have some free time. Just let me know if something like this should be handled internally by `gitbrowse` or left up to the user.

2024-11-27 15:20 UTC, krishna-bala commented
@dpetka2001 thanks for looking into this! I agree, seems reasonable to let the user handle changing `cwd` when necessary.

2024-11-27 15:27 UTC, folke requested changes

2024-11-27 15:27 UTC, folke commented on lua/snacks/gitbrowse.lua
> +  if not hash:match("^[a-fA-F0-9]+$") then
Can you add an extra check that #hash should be at least 7 characters?

2024-11-27 15:29 UTC, folke commented on lua/snacks/gitbrowse.lua
> +  system({ "git", "rev-parse", "--verify", hash }, "Invalid commit hash")
This should use the `-C cwd` param like the other checks

2024-11-27 15:31 UTC, folke commented
@dpetka2001 about that `cwd`, I wouldn't do anything special here.
Just use the cwd as detected for the other commands (which will result in the real cwd in most cases) and use that.

For sure not needed to handle opening git blame with commit hashes from another repo...

2024-11-27 17:16 UTC, dpetka2001 commented
Done.

2024-11-27 17:22 UTC, merged

2024-11-27 17:22 UTC, folke commented
ty!